import { Badge } from "./badge";

const STATUS_VARIANT: Record<string, "default" | "primary" | "success" | "warning" | "error" | "outline" | "neutral"> = {
  Aman: "success",
  "Perlu Diproses": "warning",
  Prioritas: "primary",
  "Risiko Aging": "error",
  Diterima: "outline",
  Diproses: "primary",
  "Selesai Diproses": "success",
  "Menunggu QC": "warning",
  Disetujui: "success",
  Menunggu: "warning",
  Ditolak: "error",
  Revisi: "warning",
  "Belum Dimulai": "neutral",
  "Dalam Proses": "primary",
  Selesai: "success",
  Tertunda: "error",
  Prima: "success",
  Baik: "primary",
  "Perlu Perhatian": "warning",
  Draft: "neutral",
  Terjadwal: "primary",
  Dikirim: "success",
  Terima: "success",
  Negosiasikan: "warning",
  "Produksi Selektif": "primary",
  Tolak: "error",
  // Status Aruna ERP
  "Menunggu Approval": "warning",
  Berjalan: "primary",
  Quotation: "neutral",
  Dikonfirmasi: "primary",
  Ditagih: "warning",
  Lunas: "success",
  Dibatalkan: "error",
  "Belum Jatuh Tempo": "outline",
  "Jatuh Tempo": "warning",
  Terlambat: "error",
  Hadir: "success",
  Cuti: "primary",
  Sakit: "error",
  Izin: "warning",
  "Belum Absen": "neutral",
  Terbuka: "warning",
  Dikerjakan: "primary",
  Rendah: "neutral",
  Sedang: "warning",
  Tinggi: "error",
};

export function StatusBadge({ status }: { status: string }) {
  return <Badge variant={STATUS_VARIANT[status] ?? "neutral"}>{status}</Badge>;
}
